version: "3"

services:
    links-api:
        image: baggerteam/shorty-links-api:latest
        container_name: "links-api"
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - global-network

networks:
    global-network:
        external: true
