version: "3"

services:
    front:
        image: baggerteam/shorty-client:latest
        container_name: "front"
        restart: unless-stopped
        networks:
            - proxy-network
    front-redirect:
        image: baggerteam/shorty-redirect:latest
        container_name: "front-redirect"
        restart: unless-stopped
        networks:
            - proxy-network
networks:
    proxy-network:
        external: true
